/**
 * Mock Content Batch Generator
 * ---------------------------------
 * Pure, deterministic, offline generator used only by MockProvider. Produces
 * exactly 30 ContentPieces: 10 instagram_reel + 10 facebook_post +
 * 10 youtube_short, each with piece_number 1-10 (unique within its
 * platform) and all required fields populated.
 *
 * No network calls, no randomness that could produce invalid/empty fields.
 */

import { PLATFORMS, PIECES_PER_PLATFORM, type ContentBatch, type ContentPiece, type Platform } from "./content-schema";

const PLATFORM_LABEL: Record<Platform, string> = {
  instagram_reel: "Instagram Reel",
  facebook_post: "Facebook Post",
  youtube_short: "YouTube Short",
};

function buildPiece(platform: Platform, pieceNumber: number, topic: string): ContentPiece {
  const label = PLATFORM_LABEL[platform];
  return {
    platform,
    piece_number: pieceNumber,
    title: `${label} ${pieceNumber}: ${topic}`,
    body: `[Mock] ${label} script/copy #${pieceNumber} about "${topic}". This is placeholder body text generated by MockProvider, not a real model.`,
    hashtags: [`#mock`, `#${platform}`, `#piece${pieceNumber}`],
    cta: `Learn more about ${topic} — link in bio.`,
  };
}

/**
 * Generates the full 30-piece batch. `topic` (usually the request prompt)
 * is echoed into each piece's copy so output is visibly tied to the input,
 * without adding any randomness or network dependency.
 */
export function generateMockContentBatch(topic: string): ContentBatch {
  const safeTopic = topic.trim().length > 0 ? topic.trim() : "your brand";
  const pieces: ContentPiece[] = [];

  for (const platform of PLATFORMS) {
    for (let n = 1; n <= PIECES_PER_PLATFORM; n++) {
      pieces.push(buildPiece(platform, n, safeTopic));
    }
  }

  return { pieces };
}
